"""
Report Generator API Route (Async + Auth)
==========================================
Exports analysis results as JSON or formatted PDF files.
PDF uses a premium, brand-consistent design with ReportLab.
"""

import json
import logging
from datetime import datetime
from io import BytesIO

from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.enums import TA_CENTER

from app.database import get_db
from app.models.analysis import AnalysisResult
from app.models.user import User
from app.api.deps import get_current_user

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/report", tags=["Report"])

# ─── Brand Colors ────────────────────────────────────────────
C_PRIMARY = colors.HexColor('#6366f1')
C_ACCENT = colors.HexColor('#06b6d4')
C_SUCCESS = colors.HexColor('#10b981')
C_BLOCKER = colors.HexColor('#7f1d1d')
C_CRITICAL = colors.HexColor('#ef4444')
C_HIGH = colors.HexColor('#f97316')
C_MEDIUM = colors.HexColor('#eab308')
C_LOW = colors.HexColor('#3b82f6')
C_WHITE = colors.white
C_LIGHT_BG = colors.HexColor('#f8fafc')
C_HEADER_BG = colors.HexColor('#1e1b4b')
C_TEXT_SEC = colors.HexColor('#64748b')
C_TEXT_MUT = colors.HexColor('#94a3b8')

SEV_COLOR = {
    'blocker': C_BLOCKER,
    'critical': C_CRITICAL,
    'high': C_HIGH,
    'medium': C_MEDIUM,
    'low': C_LOW,
    'info': C_TEXT_MUT,
    'trace': C_TEXT_MUT,
}


def get_score_color(score):
    if score >= 80: return C_SUCCESS
    if score >= 60: return C_MEDIUM
    if score >= 40: return C_HIGH
    return C_CRITICAL


def get_grade(score):
    if score >= 90: return 'A'
    if score >= 80: return 'B'
    if score >= 70: return 'C'
    if score >= 60: return 'D'
    return 'F'


class BrandedCanvas(canvas.Canvas):
    def __init__(self, *args, repo_name="", date_str="", **kwargs):
        super().__init__(*args, **kwargs)
        self.repo_name = repo_name
        self.date_str = date_str
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_chrome(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_chrome(self, page_count):
        page_num = self._pageNumber
        w, h = letter

        if page_num == 1:
            self.setFillColor(C_HEADER_BG)
            self.rect(0, h - 100, w, 100, fill=1, stroke=0)
            self.setFillColor(C_PRIMARY)
            self.rect(0, h - 104, w, 4, fill=1, stroke=0)
            self.setFont('Helvetica-Bold', 22)
            self.setFillColor(C_WHITE)
            self.drawString(40, h - 52, 'CodeAutopsy')
            self.setFont('Helvetica', 10)
            self.setFillColor(colors.HexColor('#a5b4fc'))
            self.drawString(40, h - 70, 'AI-Powered Security & Quality Analysis')
            self.setFont('Helvetica', 9)
            self.setFillColor(colors.HexColor('#818cf8'))
            repo_display = self.repo_name if len(self.repo_name) < 45 else '...' + self.repo_name[-42:]
            self.drawRightString(w - 40, h - 52, repo_display)
            self.setFillColor(colors.HexColor('#4f46e5'))
            self.setFont('Helvetica', 8)
            self.drawRightString(w - 40, h - 68, self.date_str)
        else:
            self.setFillColor(C_HEADER_BG)
            self.rect(0, h - 36, w, 36, fill=1, stroke=0)
            self.setFillColor(C_PRIMARY)
            self.rect(0, h - 38, w, 2, fill=1, stroke=0)
            self.setFont('Helvetica-Bold', 9)
            self.setFillColor(colors.HexColor('#a5b4fc'))
            self.drawString(40, h - 24, 'CodeAutopsy Analysis Report')
            self.setFont('Helvetica', 8)
            self.setFillColor(colors.HexColor('#6366f1'))
            self.drawRightString(w - 40, h - 24, self.repo_name)

        self.setFillColor(colors.HexColor('#f1f5f9'))
        self.rect(0, 0, w, 32, fill=1, stroke=0)
        self.setFillColor(C_PRIMARY)
        self.rect(0, 32, w, 1, fill=1, stroke=0)
        self.setFont('Helvetica', 7.5)
        self.setFillColor(C_TEXT_SEC)
        self.drawString(40, 12, f'Generated by CodeAutopsy AI  •  {self.date_str}')
        self.drawRightString(w - 40, 12, f'Page {page_num} of {page_count}')


def _make_styles():
    base = getSampleStyleSheet()
    return {
        'section': ParagraphStyle(
            'Section', parent=base['Heading2'],
            fontSize=14, fontName='Helvetica-Bold',
            textColor=C_PRIMARY, spaceBefore=24, spaceAfter=10,
        ),
        'body': ParagraphStyle(
            'Body', parent=base['Normal'],
            fontSize=9, textColor=colors.HexColor('#374151'), spaceAfter=4,
        ),
        'caption': ParagraphStyle(
            'Caption', parent=base['Normal'],
            fontSize=8, textColor=C_TEXT_SEC, spaceAfter=2,
        ),
    }


# ─── JSON Export ─────────────────────────────────────────────

@router.get("/{analysis_id}/json")
async def export_json(
    analysis_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Export analysis result as a JSON file."""
    result = await db.execute(
        select(AnalysisResult).where(AnalysisResult.id == analysis_id)
    )
    analysis = result.scalar_one_or_none()
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    if analysis.status != "complete":
        raise HTTPException(status_code=400, detail="Analysis is not yet complete")

    issues = analysis.get_issues()
    sev_summary = {
        "blocker": 0,
        "critical": 0,
        "high": 0,
        "medium": 0,
        "low": 0,
        "info": 0,
        "trace": 0,
    }
    for i in issues:
        s = i.get("severity", "info")
        sev_summary[s] = sev_summary.get(s, 0) + 1

    analyzed_at = (
        analysis.completed_at.isoformat() if analysis.completed_at
        else (analysis.created_at.isoformat() if analysis.created_at
              else datetime.utcnow().isoformat())
    )

    export_data = {
        "metadata": {
            "repository": analysis.repo_url,
            "analysis_id": analysis.id,
            "analyzed_at": analyzed_at,
            "generator": "CodeAutopsy AI v2.0",
        },
        "summary": {
            "health_score": analysis.health_score or 0,
            "total_files": analysis.file_count or 0,
            "total_lines": analysis.total_lines or 0,
            "total_issues": analysis.total_issues or 0,
            "severity_summary": sev_summary,
        },
        "issues": issues,
        "ollama_findings": analysis.get_ollama_findings(),
        "file_tree": analysis.get_file_tree(),
    }

    return Response(
        content=json.dumps(export_data, indent=2),
        media_type="application/json",
        headers={
            "Content-Disposition": (
                f'attachment; filename="codeautopsy_report_{analysis_id[:8]}.json"'
            )
        },
    )


# ─── PDF Export ──────────────────────────────────────────────

@router.get("/{analysis_id}/pdf")
async def export_pdf(
    analysis_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Export analysis result as a branded PDF report."""
    result = await db.execute(
        select(AnalysisResult).where(AnalysisResult.id == analysis_id)
    )
    analysis = result.scalar_one_or_none()
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    if analysis.status != "complete":
        raise HTTPException(status_code=400, detail="Analysis is not yet complete")

    issues = analysis.get_issues()
    severity_order = {
        "blocker": 0,
        "critical": 1,
        "high": 2,
        "medium": 3,
        "low": 4,
        "info": 5,
        "trace": 6,
    }
    issues.sort(key=lambda x: severity_order.get(x.get("severity", "info"), 99))

    repo_name = analysis.repo_url.split('github.com/')[-1].strip('/')
    if analysis.completed_at:
        date_str = analysis.completed_at.strftime("%B %d, %Y at %H:%M UTC")
    elif analysis.created_at:
        date_str = analysis.created_at.strftime("%B %d, %Y at %H:%M UTC")
    else:
        date_str = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")

    sev_counts = {
        "blocker": 0,
        "critical": 0,
        "high": 0,
        "medium": 0,
        "low": 0,
        "info": 0,
        "trace": 0,
    }
    for i in issues:
        s = i.get("severity", "info")
        sev_counts[s] = sev_counts.get(s, 0) + 1

    health_score = analysis.health_score or 0
    grade = get_grade(health_score)
    score_color = get_score_color(health_score)

    buffer = BytesIO()
    S = _make_styles()

    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        rightMargin=40, leftMargin=40,
        topMargin=116, bottomMargin=48,
        title=f"CodeAutopsy Report — {repo_name}",
        author="CodeAutopsy AI",
    )

    def canvas_maker(*args, **kwargs):
        return BrandedCanvas(*args, repo_name=repo_name, date_str=date_str, **kwargs)

    elems = []

    # Executive Summary
    elems.append(Paragraph("Executive Summary", S['section']))
    stat_data = [
        ['Health Score', 'Grade', 'Total Issues', 'Files Analyzed', 'Lines of Code'],
        [f'{health_score}/100', grade, str(len(issues)),
         str(analysis.file_count or 0), f"{(analysis.total_lines or 0):,}"]
    ]
    col_widths = [1.2*inch, 0.8*inch, 1.2*inch, 1.3*inch, 1.3*inch]
    stat_table = Table(stat_data, colWidths=col_widths, hAlign='LEFT')
    stat_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), C_HEADER_BG),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#a5b4fc')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 8),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 1), (-1, 1), 16),
        ('TEXTCOLOR', (0, 1), (0, 1), score_color),
        ('TEXTCOLOR', (1, 1), (1, 1), score_color),
        ('TEXTCOLOR', (2, 1), (2, 1),
         C_BLOCKER if sev_counts.get('blocker', 0) > 0
         else (C_CRITICAL if sev_counts.get('critical', 0) > 0 else C_SUCCESS)),
        ('TEXTCOLOR', (3, 1), (3, 1), colors.HexColor('#374151')),
        ('TEXTCOLOR', (4, 1), (4, 1), colors.HexColor('#374151')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 1), (-1, 1), [C_LIGHT_BG]),
    ]))
    elems.append(stat_table)
    elems.append(Spacer(1, 20))

    # Severity Breakdown
    elems.append(Paragraph("Issue Breakdown by Severity", S['section']))
    sev_order = ["blocker", "critical", "high", "medium", "low", "info", "trace"]
    sev_rows = []
    total_issues_count = max(len(issues), 1)
    for sev in sev_order:
        count = sev_counts.get(sev, 0)
        pct = int((count / total_issues_count) * 100)
        sev_rows.append([sev.upper(), str(count), f'{pct}%'])

    sev_header = [['Severity', 'Count', 'Proportion']]
    sev_table = Table(sev_header + sev_rows, colWidths=[1.5*inch, 1*inch, 1*inch], hAlign='LEFT')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), C_HEADER_BG),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#a5b4fc')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 8),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]
    for row_i, sev in enumerate(sev_order):
        r = row_i + 1
        style_cmds.append(('BACKGROUND', (0, r), (-1, r), C_LIGHT_BG if row_i % 2 == 0 else colors.white))
        style_cmds.append(('TEXTCOLOR', (0, r), (0, r), SEV_COLOR.get(sev, C_TEXT_MUT)))
    sev_table.setStyle(TableStyle(style_cmds))
    elems.append(sev_table)
    elems.append(Spacer(1, 24))

    # Issues Table (top 100)
    elems.append(Paragraph("Detected Issues (Top 100)", S['section']))
    if not issues:
        elems.append(Paragraph(
            "<font color='#10b981'>✓ No issues found. Excellent work!</font>", S['body']
        ))
    else:
        issue_header = [['#', 'Severity', 'Family', 'File', 'Line']]
        issue_rows = []
        for idx, issue in enumerate(issues[:100], 1):
            file_name = issue.get('file_path', '')
            parts = file_name.replace('\\', '/').split('/')
            file_display = '/'.join(parts[-2:]) if len(parts) > 1 else file_name
            if len(file_display) > 32:
                file_display = '…' + file_display[-30:]
            issue_type = issue.get('defect_family', 'unknown')
            if len(issue_type) > 28:
                issue_type = issue_type[:26] + '…'
            sev = issue.get('severity', 'info')
            issue_rows.append([str(idx), sev.upper(), issue_type, file_display, str(issue.get('line_number', '?'))])

        issue_table = Table(
            issue_header + issue_rows,
            colWidths=[0.35*inch, 0.75*inch, 2.3*inch, 2.3*inch, 0.45*inch],
            hAlign='LEFT', repeatRows=1,
        )
        issue_style = [
            ('BACKGROUND', (0, 0), (-1, 0), C_HEADER_BG),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#a5b4fc')),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('ALIGN', (0, 1), (1, -1), 'CENTER'),
            ('ALIGN', (-1, 1), (-1, -1), 'CENTER'),
            ('FONTNAME', (3, 1), (3, -1), 'Courier'),
            ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#e5e7eb')),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]
        sev_c_map = {
            'BLOCKER': C_BLOCKER,
            'CRITICAL': C_CRITICAL,
            'HIGH': C_HIGH,
            'MEDIUM': colors.HexColor('#a16207'),
            'LOW': C_LOW,
            'INFO': C_TEXT_MUT,
            'TRACE': C_TEXT_MUT,
        }
        for row_i, issue in enumerate(issues[:100], 1):
            sev = issue.get('severity', 'info').upper()
            if row_i % 2 == 0:
                issue_style.append(('BACKGROUND', (0, row_i), (-1, row_i), colors.HexColor('#f9fafb')))
            issue_style.append(('TEXTCOLOR', (1, row_i), (1, row_i), sev_c_map.get(sev, C_TEXT_MUT)))
            issue_style.append(('FONTNAME', (1, row_i), (1, row_i), 'Helvetica-Bold'))
        issue_table.setStyle(TableStyle(issue_style))
        elems.append(issue_table)
        if len(issues) > 100:
            elems.append(Spacer(1, 8))
            elems.append(Paragraph(f"<i>… and {len(issues) - 100} more issues not shown.</i>", S['caption']))

    elems.append(Spacer(1, 32))
    elems.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#e5e7eb')))
    elems.append(Spacer(1, 8))
    elems.append(Paragraph(
        f"This report was generated by CodeAutopsy AI v2.0. "
        f"Repository: <b>{repo_name}</b>  •  Analysis ID: {analysis_id[:8]}",
        S['caption']
    ))

    doc.build(elems, canvasmaker=canvas_maker)

    return Response(
        content=buffer.getvalue(),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="codeautopsy_{repo_name.replace("/", "_")}.pdf"'
        },
    )
