"""add_contributor_stats

Revision ID: 26394a479e5c
Revises: 20260406_0004
Create Date: 2026-04-07 13:51:33.543036
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26394a479e5c'
down_revision = '20260406_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('contributor_stats', sa.Text(), nullable=True))
    op.alter_column('analysis_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analysis_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analysis_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_analysis_rules_rule_id', table_name='analysis_rules')
    op.create_index('ix_analysis_rules_rule_id', 'analysis_rules', ['rule_id'], unique=False)
    op.create_unique_constraint(None, 'analysis_rules', ['rule_id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'analysis_rules', type_='unique')
    op.drop_index('ix_analysis_rules_rule_id', table_name='analysis_rules')
    op.create_index('ix_analysis_rules_rule_id', 'analysis_rules', ['rule_id'], unique=True)
    op.alter_column('analysis_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('analysis_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('analysis_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('analysis_results', 'contributor_stats')
    # ### end Alembic commands ###
